name: "Generate Speech Audio From txt Files"
description: Run the inline txt2sp pipeline to synthesize host and guest audio.
inputs:
  speech_key:
    description: Azure Speech resource key.
    required: true
  endpoint_url:
    description: Azure Speech endpoint URL.
    required: true
  host_voice:
    description: Host voice name for synthesis.
    default: "en-US-Ava:DragonHDLatestNeural"
    required: false
  guest_voice:
    description: Guest voice name for synthesis.
    default: "en-US-Andrew:DragonHDLatestNeural"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Azure Speech SDK
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install "azure-cognitiveservices-speech>=1.36.0"

    - name: Generate audio
      shell: python
      working-directory: ${{ github.workspace }}
      env:
        SPEECH_KEY: ${{ inputs.speech_key }}
        ENDPOINT_URL: ${{ inputs.endpoint_url }}
        HOST_VOICE: ${{ inputs.host_voice }}
        GUEST_VOICE: ${{ inputs.guest_voice }}
      run: |
        import os
        from pathlib import Path

        from speech_library import SCRIPTS_ROOT, synthesize_text_file


        def _require_env(var_name: str) -> str:
            value = os.environ.get(var_name)
            if not value:
                raise RuntimeError(f"Please set the {var_name} environment variable.")
            return value


        def _process_directory(source_dir: Path, voice: str) -> None:
            if not source_dir.exists():
                raise FileNotFoundError(f"Source directory not found: {source_dir}")
            for text_file in sorted(source_dir.rglob("*.txt")):
                output_path = synthesize_text_file(text_file, voice)
                print(f"Speech synthesized to [{output_path}] for text file [{text_file}]")


        host_voice = _require_env("HOST_VOICE")
        guest_voice = _require_env("GUEST_VOICE")
        _require_env("SPEECH_KEY")
        _require_env("ENDPOINT_URL")

        _process_directory(SCRIPTS_ROOT / "host", host_voice)
        _process_directory(SCRIPTS_ROOT / "guest", guest_voice)
