name: "Generate Speech Audio From txt Files"
description: Run the inline txt2sp pipeline to synthesize host and guest audio.
inputs:
  speech_key:
    description: Azure Speech resource key.
    required: true
  endpoint_url:
    description: Azure Speech endpoint URL.
    required: true
  voice:
    description: Voice name for synthesis.
    default: "en-US-Ava:DragonHDLatestNeural"
    required: false
  text_directory:
    description: Relative or absolute path to the directory containing .txt files to synthesize.
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Azure Speech SDK
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install "azure-cognitiveservices-speech>=1.36.0"

    - name: Generate audio
      shell: python
      working-directory: ${{ github.workspace }}
      env:
        SPEECH_KEY: ${{ inputs.speech_key }}
        ENDPOINT_URL: ${{ inputs.endpoint_url }}
        VOICE: ${{ inputs.voice }}
        TEXT_DIRECTORY: ${{ inputs.text_directory }}
        PYTHONPATH: ${{ github.action_path }}
      run: |
        import os
        from pathlib import Path

        from speech_library import synthesize_text_file


        def _require_env(var_name: str) -> str:
            value = os.environ.get(var_name)
            if not value:
                raise RuntimeError(f"Please set the {var_name} environment variable.")
            return value


        def _process_directory(source_dir: Path, voice: str) -> None:
            if not source_dir.exists():
                raise FileNotFoundError(f"Source directory not found: {source_dir}")
            for text_file in sorted(source_dir.rglob("*.txt")):
                output_path = synthesize_text_file(text_file, voice)
                print(f"Speech synthesized to [{output_path}] for text file [{text_file}]")

        def _resolve_text_directory() -> Path:
          raw_dir = _require_env("TEXT_DIRECTORY")
          directory = Path(raw_dir)
          if not directory.is_absolute():
            directory = Path.cwd() / directory
          directory = directory.resolve()
          if not directory.exists():
            raise FileNotFoundError(f"Text directory not found: {directory}")
          return directory


        voice = _require_env("VOICE")
        _require_env("SPEECH_KEY")
        _require_env("ENDPOINT_URL")
        text_directory = _resolve_text_directory()

        _process_directory(text_directory, voice)
